config:
  experiment_name: "hourse_grass"
  block: "output_block_11" # the module name of the visualized features (e.g. "output_block_4", "input_block_7").
  experiments_fit: # the list of the experiments to visualize the features for
    - "hourse_grass"
      #- "cute_cat"
      #- "unhappy_happy_cat"
      #- "old_new_car"
      #- "house_cat"
  experiments_transform: # the list of the experiments used for calculating the principal components
    - "hourse_grass"
      #- "cute_cat"
      #- "unhappy_happy_cat"
      #- "old_new_car"
      #- "house_cat"
